apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.postgresqlUsername }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresql.postgresqlPassword }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresql.postgresqlDatabase }}"
          ports:
            - containerPort: {{ .Values.postgresql.service.port }}
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          env:
            # Pass JDBC-related environment variables to backend service
            - name: JDBC_DATABASE_USERNAME
              value: "{{ .Values.postgresql.postgresqlUsername }}"
            - name: JDBC_DATABASE_PASSWORD
              value: "{{ .Values.postgresql.postgresqlPassword }}"
            - name: JDBC_DATABASE_URL
              value: "{{ .Values.backend.url }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          env:
            - name: API_PATH
              value: "{{ .Values.frontend.apiPath }}"
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
        
