apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.targetPort }}
  type: {{ .Values.postgresql.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  type: {{ .Values.backend.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  type: {{ .Values.frontend.service.type }}


